### ISSUE TITLE
Preliminary Python Code

### ISSUE THREAD

**Issue by JessyD** [OpenSourceBrain/WilsonCowan#1]
I have created the a Python script (https://github.com/OpenSourceBrain/WilsonCowan/commit/56b09332fa6013bea8eeb39d03b5bef0d541f9e5) with the same variables definitions as in the `wc.mod`.  However, already after the second iteration the values for uu' and vv' diverge between the 2 implementations.  I have added some print statements to look at the progression of vv' and uu' over time on the neuron code (you should be able to see it if you run `nrnivmodl` and
`nrngui wc.hoc`) and I realised that:
1. The progression of `dt` is not constant. Is this a standard definition in neuron?
2.  I would expect the values of uu(t) to correspond to uu'(t-1), however, looking at the printed output from neuron uu is being updated but the value does not correspond to uu' of the previous iteration. Am I missing something important?

Additionally, I thought that the Wilson and Cowan equations also included the a parameter that takes into account the active cells and their refractory period. Therefore, I would expect the main equation to look something like:
```
uu' = (- uu + (1 - r*uu) * f(w_ee * uu - w_ei * vv))/tau
vv' = (-vv + (1 - r*vv) * f(w_ie * uu - w_ii * vv))/tau
```

**Comment by pgleeson** [comment]
@JessyD Note that the uu' and vv' are the rates of change of the variables uu and vv, so you'll have to calculate the deltas for rates as in the delmolino example:

        dr = dt * (-r + calculate_phi(V, Vth, Vr)) / tau_r
        r = r + dr

This is a very simple numerical integration scheme but should suffice if dt is small.

Re dt in Neuron, it does vary, and this can be changed by Tools->VariableStepControl. Also open Tools->RunControl to see dt etc. See:

![image](https://user-images.githubusercontent.com/1556687/41101478-2d83f850-6a5c-11e8-84ef-09e45c50b573.png)

The graphs are smoother with this small dt.
