### ISSUE TITLE
Add 3D positions for E/I pops

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/WilsonCowan#2]
To facilitate visualising/replaying on OSB (red-E, blue-I). Will require move to populationList, etc.

**Comment by JessyD** [comment]
[Done](https://github.com/OpenSourceBrain/WilsonCowan/blob/development/NeuroML2/GenerateWilsonCowanLEMS.py)

For the moment I used random numbers to specify the position of the population.
